### ISSUE TITLE
Tag only with ST4 on Package Control

### ISSUE THREAD

**Issue by azizk** [elixir-editors/elixir-sublime-syntax#44]
Hi!

It would be nice if our page at https://packagecontrol.io/packages/ElixirSyntax only displayed support for ST4. :+1:

PS.: After a little hiatus I'm about to complete a new release. Do you have some time to check it? Two major things: 1. Proper highlighting of argument clauses in a `for` statement. 2. Commands for running `mix test` in various ways.

**Comment by princemaple** [comment]
Do we no longer support previous versions?

**Comment by azizk** [comment]
Not really. The st3 branch still exists but we're not really keeping an eye on it. Is it even installable from ST3? Regardless, it's too much effort to support it as well I think.

**Comment by princemaple** [comment]
Right

**Comment by princemaple** [comment]
I'll do the update after the transfer is done.
