### ISSUE TITLE
Moving this project to "elixir-editors"

### ISSUE THREAD

**Issue by azizk** [elixir-editors/elixir-sublime-syntax#45]
I think it's best if we moved this repo to [elixir-editors](https://github.com/elixir-editors/).

It's bound to get more exposure there and I don't see a point in having a separate organization just for this repo. We should request José to retire the good old elixir-tmbundle package or at least give our plugin the spotlight. If you compare the stats on [Package Control - ElixirSyntax](https://packagecontrol.io/packages/ElixirSyntax) with [Package Control - Elixir](https://packagecontrol.io/packages/Elixir) you'll see that we have a lot fewer downloads overall, which is kinda silly. Perhaps people still using ST3? Maybe but I doubt it.

On a related note I'd like to mention that I have plans for moving away from Sublime Text completely. I recently discovered [lapce](https://github.com/lapce/lapce) (my fork: [lapiz](https://github.com/azizk/lapiz)) and I believe it has the potential to become the best GUI code editor out there.\
Three reasons for me: 1. Open-source; 2. Written in Rust; 3. Uses tree-sitter.

This shouldn't be taken as a resignation, because it will take a long while until lapce is mature enough and until I'm happy enough with its UX and its feature set. However, it means I will invest the majority of my time in lapce, because unfortunately ST is simply a dead end. It will probably never use tree-sitter. Even if it suddenly became open-source and they tried to integrate tree-sitter it would be way too late. Besides, I honestly don't think we should still be writing software in C/C++ let alone a Python plugin system on top of it. Anyway, despite all the issues I have with ST I still quite like it and will continue using it until the alternative provides a day-to-day frictionless working experience. :slightly_smiling_face:

**Comment by princemaple** [comment]
I don't mind. I've sent Jose an invite to become an admin and process the transfer.

**Comment by azizk** [comment]
Thanks! José agreed as well. That's great! :+1:

**Comment by azizk** [comment]
We did it! Thanks @princemaple and @josevalim! :tada:
