### ISSUE TITLE
Broken syntax highlighting when comments are inside eex tags `<% # %>`

### ISSUE THREAD

**Issue by danglduy** [elixir-editors/elixir-sublime-syntax#47]
I am facing an issue when using `#` inside eex tags to comment codes
```
<li><%= # link("Settings", to: Routes.user_settings_path(@conn, :edit)) %></li>
```
should appear correctly as
```heex
<li><%= # link("Settings", to: Routes.user_settings_path(@conn, :edit)) %></li>
```
or VSCode
<img width="928" alt="image" src="https://user-images.githubusercontent.com/38782010/191765850-30f79154-09be-4efc-ac37-b2c11a936f07.png">

But on SublimeText the syntax highlighting is broken and shows the rest of the line as being commented out
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/38782010/191765728-b8ef35b2-09ab-42ee-8130-9074d6be1f78.png">

**Comment by princemaple** [comment]
https://github.com/elixir-lang/elixir/blob/v1.14.0/lib/eex/lib/eex.ex#L72

Does this work?

**Comment by danglduy** [comment]
There is no effect hinting that the code inside is being ignored.
<img width="865" alt="image" src="https://user-images.githubusercontent.com/38782010/191770852-e6105123-e9ca-4929-a8a3-a1656f558f70.png">

VSCode (Ignore the warning, `mix format` has some issues with the code but the code is compiled successfully.)
<img width="826" alt="image" src="https://user-images.githubusercontent.com/38782010/191771042-072f642b-205b-41eb-8418-d3c6284ee603.png">

GitHub
```heex
    <li><%!-- link("Log in", to: Routes.user_session_path(@conn, :new)) --%></li>
```

**Comment by danglduy** [comment]
Glad to hear that.
