### ISSUE TITLE
Why do .eex files not get formatted when saved?

### ISSUE THREAD

**Issue by benonymus** [elixir-editors/elixir-sublime-syntax#51]
Hey,

When I have mix_format on_save: true, regular elixir files get formatted as expected but .heex files not.

Is there any way to format them on save?

Thanks!

**Comment by benonymus** [comment]
Hey, 

That was quick! 
Yes you need changes to the project's `.formatter.exs`

https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html#module-setup

**Comment by azizk** [comment]
You're welcome! Okay, now it works. :smile: :+1:
