### ISSUE TITLE
Configuring `is_formattable_syntax`

### ISSUE THREAD

**Issue by saveman71** [elixir-editors/elixir-sublime-syntax#58]
I'm using a custom syntax that extends one from this project (see at the bottom of https://github.com/SublimeText/AlpineJS)

```
%YAML 1.2
---
# http://www.sublimetext.com/docs/syntax.html
name: HTML (HEEx, AlpineJS)
scope: text.html.heex.alpinejs
version: 2

extends:
  - Packages/ElixirSyntax/syntaxes/HTML (HEEx).sublime-syntax
  - Packages/AlpineJS/Syntaxes/HTML (AlpineJS).sublime-syntax
```

How would we go about configuring this static list so that any user extended syntax can be formatted?
https://github.com/elixir-editors/elixir-sublime-syntax/blob/6122ca0b72acab70d130d476a64dc62d62446afa/commands/utils.py#L31-L33

**Comment by azizk** [comment]
I changed it so that scope suffixes like `heex` are searched for. That should cover a lot of cases and avoids adding an extra setting. :+1:

**Comment by saveman71** [comment]
I completely missed your comment & fix !

I have been happily auto-formatting my heex files ever since, without even remembering there was a problem in the first place. Thank you so much! :pray: :partying_face:
