### ISSUE TITLE
"Find symbol in project" does not show nested modules

### ISSUE THREAD

**Issue by dmitrydprog** [elixir-editors/elixir-sublime-syntax#60]
Hi, thanks for work.

I have a large code base with many nested modules. I often use sublime function "find symbol in project".
But sublime show only tail name, it make difficult find deep nested modules.

For example, i have set of modules:
`Foo.A.B.C.D.E.Repo`
`Bar.A.B.C.D.E.Repo`
`Buzz.A.B.C.D.E.Repo`

When i call "find symbol in project" and type Repo, i see only one variant, but i would like start with: "Foo.A.B" and see what modules are there.

<img width="694" alt="image" src="https://github.com/elixir-editors/elixir-sublime-syntax/assets/10886027/8072f728-530e-4fe2-8202-33d3e1afe0c1">

Click enter

<img width="683" alt="image" src="https://github.com/elixir-editors/elixir-sublime-syntax/assets/10886027/ea7b53e8-b5ca-4c83-80a7-531fcf960643">

For fix it i changed it rule:

```
variables:
  module_name: '[A-Z][a-zA-Z\d_]*+'
  atom_id_suffix: '[\w@]*+[?!]?+'
```

To:

```
variables:
  module_name: '[A-Z][\.?[A-Za-z\d_]+]*+' # <---------------
  atom_id_suffix: '[\w@]*+[?!]?+'
```

Now i can use fuzzy search like that:

<img width="775" alt="image" src="https://github.com/elixir-editors/elixir-sublime-syntax/assets/10886027/977455e5-65f7-4e89-b629-969c52fe8bfb">

Or if I want to restrict the search starting from:

<img width="765" alt="image" src="https://github.com/elixir-editors/elixir-sublime-syntax/assets/10886027/2948e821-0a82-41b7-bab9-03ad5f0625c5">

But it break sublime goto, previously, i could put the cursor on the last part of the module name and press goto, now I can't, I have to select the module as a whole.

Maybe there is some way to fix it?

**Comment by princemaple** [comment]
That's tough luck... When the entity is indexed as a whole, the goto function doesn't find it. It appears that the goto function is not entity/syntax scoped. There might be better luck asking on Sublime Discord. https://forum.sublimetext.com/t/sublime-text-discord-server/26063

**Comment by azizk** [comment]
Yeah, I agree, it's tough luck. Not much we can do about it. It's a limitation of Sublime Text and I doubt they're gonna fix this or enhance it any time soon. It should ideally get the list of all symbols from the language server and maybe prioritize the module name over its fully qualified name when filtering...

**Comment by azizk** [comment]
Closing this because there's no real solution afaik.
