### ISSUE TITLE
Comments in heex files and ~H"""

### ISSUE THREAD

**Issue by jg70** [elixir-editors/elixir-sublime-syntax#63]
According to [https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html#module-comments](url) would it be possible to change the line comments for heex-files and within ~H""" to

`<%!-- commented line --%>`

Currently you got

`<!-- commented line -->`

**Comment by azizk** [comment]
I'll check :)

**Comment by jg70** [comment]
> I'll check :)

TOP! 
thanks a lot!

**Comment by azizk** [comment]
I can see it's being recognized:

![image](https://github.com/elixir-editors/elixir-sublime-syntax/assets/37282/d7b532df-2b59-4ef0-a520-d07f41add909)

But the `<%` and `%>` punctuation marks should probably be styled differently.

**Comment by jg70** [comment]
> I can see it's being recognized:
> 
> ![image](https://user-images.githubusercontent.com/37282/260221440-d7b532df-2b59-4ef0-a520-d07f41add909.png)
> 
> But the `<%` and `%>` punctuation marks should probably be styled differently.

Yeah, it's recognized perfectly. What I mean is, that when you toggle a comment in sublime with cmd+shift+slash then the command results in `<!-- commented line -->`

**Comment by azizk** [comment]
Oh, gotchya! Let's see how to do that :)

**Comment by jg70** [comment]
> Oh, gotchya! Let's see how to do that :)

top ;-)
